### ISSUE TITLE
Problem of assert when adding RcppArmadillo code.

### ISSUE THREAD

**Issue by privefl** [RcppCore/RcppArmadillo#116]
I added [some RcppArmadillo code](https://github.com/privefl/bigstatsr/blob/12ae8b7927d41428fd05edbfb5d37194ab7ff56c/src/univRegLin2.cpp) to [my package](https://github.com/privefl/bigstatsr/tree/12ae8b7927d41428fd05edbfb5d37194ab7ff56c) and it resulted in a warning during checking:
```
checking compiled code ... WARNING
File ‘bigstatsr/libs/bigstatsr.so’:
  Found ‘__assert_fail’, possibly from ‘assert’ (C)
    Object: ‘RcppExports.o’
```
You can see Travis-CI results [there](https://travis-ci.org/privefl/bigstatsr/jobs/185704884).

I am on CentOS 7 (Linux) with version 3.3.1 of R (Travis-CI tests oldrel, release and devel) and tried with both the latest and previous versions of RcppArmadillo (0.7.600.1.0 & 0.7.500.0.0).

I really don't know how to handle this error as I don't use any `#include <assert.h>` and, when checking, R uses the `-DNDEBUG` flag. 
Any help would be really appreciated.

**Comment by eddelbuettel** [comment]
Weird.  We now have 301 CRAN packages using RcppArmadillo, and that has not come up elsewhere.  It is likely an interaction with your headers.

I think the standard trick is indeed to revert the `NDEBUG` macro, see eg [here](http://stackoverflow.com/questions/389180/assert-and-ndebug) or [here](http://stackoverflow.com/questions/6492668/assert-ndebug-and-segmentation-fault) so adding an `#undef NDEBUG` should do.

As should placing `#include <RcppArmadillo.h>` last.  Can you try some of those?

**Comment by privefl** [comment]
I've tried to switch headers, no change.
I've tried to put `#undef NDEBUG` in `inst/include/bigstatsr.h` so that it is include in RcppExports. I didn't see any change (don't know what changes I should see?). I'm a bit confused because I don't use any `assert` myself. 

Maybe there are some problems (of compatibility), so
- I tested [bigalgebra](https://github.com/cdeterman/bigalgebra) which uses `bigmemory`. I don't have this problem (yet other problems),
- I tested [BigVAR](https://cran.r-project.org/web/packages/BigVAR/index.html) which uses `RcppEigen`. I also don't have this problem.

Really have no idea :/

**Comment by eddelbuettel** [comment]
You need to ensure `NDEBUG` is set the way it needs to be set to _avoid_ using `assert()` _for the compilation unit showing the error_.

**Comment by eddelbuettel** [comment]
I just checked it out. I am a little stunned too.  

Can you try to look at the few other packages using RcppArmadillo _and_ RcppEigen?

**Comment by eddelbuettel** [comment]
FWIW I do not have `assert` come out of a call of `strings` on the libraries for RcppArmadillo, RcppEigen or bigmemory.

**Comment by privefl** [comment]
There are also
- [BacArena](https://cran.r-project.org/web/packages/BacArena/index.html) but it needs GLPK and a yum install didn't fix this.
- [gRain](https://cran.r-project.org/web/packages/gRain/index.html) but I also have some problems during the installation.
- [oem](https://cran.r-project.org/web/packages/oem/index.html)
- [perccal](https://cran.r-project.org/web/packages/perccal/index.html)
- [Rvcg](https://cran.r-project.org/web/packages/Rvcg/index.html)
I will look into these last 3 when I have the time.

**Comment by thirdwing** [comment]
From the object file,

```
_ZNK4arma5SpMatIjE9head_rowsEj^@_ZNK4arma3MatIdE8each_colEv^@__assert_fail
```

The `assert_fail` seems from `arma`

**Comment by eddelbuettel** [comment]
Ahh, good, so `-DARMA_NO_DEBUG` may be what we need.

**Comment by thirdwing** [comment]
The devel version of R still fails. Really weird to me.

https://travis-ci.org/privefl/bigstatsr/builds/185879133

**Comment by eddelbuettel** [comment]
I have it in /tmp on a 16.04 box here.  I too am stumped.

**Comment by eddelbuettel** [comment]
The [oem](https://cran.r-project.org/web/packages/oem/index.html) does not show the problem, and also uses 

```
LinkingTo: 
    Rcpp, 
    RcppEigen, 
    BH, 
    bigmemory, 
    RcppArmadillo
```

It has `PKG_CXXFLAGS = -DNDEBUG` in `src/Makevars`.  I could swear I tried that already.

**Comment by eddelbuettel** [comment]
But it doesn't use `RcppExports.cpp`.  I still have the feeling that has something to do with it.

**Comment by eddelbuettel** [comment]
Ok, using a _really big hammer_ I got it to behave. 

Some `NDEBUG` gets undefined in the header [here](https://github.com/RcppCore/RcppArmadillo/blob/master/inst/include/RcppArmadilloConfig.h#L82-L86) and that somehow creates an issue.  No other package I know of has been bitten.

Using 

```
#include <RcppArmadillo.h>
#define NDEBUG 1
#include <RcppEigen.h>
#include <Rcpp.h>
```

at the top of RcppExports.cpp works.  That obviously doesn't scale well.  

The best I can think of is another define we set, maybe `-DREALLY_KEEP_NDEBUG` to condition out the segment I pointed to above.  Not sure.

For now,  handediting `RcppExports.cpp` is the best bet.

**Comment by privefl** [comment]
This works!
https://github.com/privefl/bigstatsr/commit/9782645a6270d69df648462332587218ae41acbd

**Comment by privefl** [comment]
Thanks both!

**Comment by eddelbuettel** [comment]
_tl;dr summary_  There is an `undef` of `NDEBUG` one may need to undo.  Adding the definition to the compiler flags along does not help as the file-based directives comes later in the process and override them too.

**Comment by aitap** [comment]
In my opinion, [this problem recently discussed on R-package-devel](https://stat.ethz.ch/pipermail/r-package-devel/2022q4/008641.html) has been caused by the `#undef NDEBUG` line in [`inst/include/RcppArmadillo/config/RcppArmadilloConfig.h`](https://github.com/RcppCore/RcppArmadillo/blob/1a0174a3ff5ee22b8aaa689dac4068b9d34603bf/inst/include/RcppArmadillo/config/RcppArmadilloConfig.h#L90-L94) (not an upstream file). Does anything in current RcppArmadillo check for `NDEBUG`? Maybe I'm [searching wrong](https://github.com/RcppCore/RcppArmadillo/search?q=NDEBUG&type=code), but I don't see anything.

While it's true that R is set up to disable `assert()` by defining `NDEBUG` at the compiler command line, the `#undef` gets processed after the command line switches and hides the `NDEBUG` symbol for any code that follows `#include <RcppArmadillo.h>`.

Even then, that's not a problem for most users of RcppArmadillo. In order to trigger it, the user has to  `#include <assert.h>` after `<RcppArmadillo.h>`, while not having included `<assert.h>` before `<RcppArmadillo.h>`. Otherwise, either the include guards would prevent `assert.h` from being processed a second time, resulting in a `#define assert(x) (void)0` from the first inclusion, or there's no `assert` to cause trouble in the first place.

I'd like to highlight Aristide's fix: the problem goes away in packages that use both RcppNumerical and RcppArmadillo when there's `#define NDEBUG` after `#include <RcppArmadillo.h>`. Not sure where `<cassert>` is included, but [here](https://github.com/yixuan/RcppNumerical/blob/912d13f4483bc276a26bc1aa1b93d04306915387/inst/include/optimization/LBFGS/LineSearchBracketing.h#L99)'s one of the two `assert()`s in RcppNumerical that Aristide may have stumbled upon. I think that many packages that  `#include <RcppArmadillo.h>` don't include anything that can `assert()` at all, which lowers of chances of the problem showing up even further, resulting in the rate of once every 3-4 years :)

If there's still a need for `#undef NDEBUG` in RcppArmadillo, the defined-ness of `NDEBUG` could be preserved outside RcppArmadillo by something like the following:

```c
// RcppArmadilloConfig.h:
#ifdef NDEBUG
 #define RCPPARMADILLO_UNDEFINED_NDEBUG_
 #undef NDEBUG
#endif
// at the end of RcppArmadillo public headers:
#ifdef RCPPARMADILLO_UNDEFINED_NDEBUG_
 #define NDEBUG
#endif
```

(The value of NDEBUG is still lost, but that shouldn't be a problem.)

Here's a reproducer:
```c++
#ifndef NDEBUG
	#error Please compile this with -DNDEBUG
#endif

#include <RcppArmadillo.h>
//#define NDEBUG
#include <RcppNumerical.h>

// [[Rcpp::depends(RcppArmadillo)]]
// [[Rcpp::depends(RcppEigen)]]
// [[Rcpp::depends(RcppNumerical)]]
// [[Rcpp::export(runme)]]
int runme() {
	assert(0);
}
```

It won't compile without `-DNDEBUG` (but it does compile with `sourceCpp` on my machine), and yet it does crash the R session unless I uncomment `#define NDEBUG`.

**Comment by eddelbuettel** [comment]
Yes that could play a role and I think we set it up this way ages ago because it was (entirely correctly) pointed out that it is better to have some asserts (the view of upstream) to catch potential issues.  At the same time R Core is entirely correct to not want `assert()` in dynamically loaded code because we generally do _not_ want to kill our entire R session.  So the on/off scheme you produce could work.

I am generally somewhat conservative relative to change here.  What we setup here is unchanged for years and the package is in good standing at CRAN, and with its users.  So I am unconvinced me need to rock any boats.

**Comment by eddelbuettel** [comment]
It is from April 2012 and has not changed in 10 1/2 years: 

https://github.com/RcppCore/RcppArmadillo/blame/1a0174a3ff5ee22b8aaa689dac4068b9d34603bf/inst/include/RcppArmadillo/config/RcppArmadilloConfig.h#L90-L95

**Comment by eddelbuettel** [comment]
Can you check that a simple reorder works:

```c++
#ifndef NDEBUG
	#error Please compile this with -DNDEBUG
#endif

#include <RcppNumerical.h>
#include <RcppArmadillo.h>

// [[Rcpp::depends(RcppArmadillo)]]
// [[Rcpp::depends(RcppEigen)]]
// [[Rcpp::depends(RcppNumerical)]]
// [[Rcpp::export(runme)]]
int runme() {
	assert(0);
	return 0;
}
```

**Comment by aitap** [comment]
Sorry, not sure whether this is related, but I get an error message in this case:
```
/usr/lib/R/bin/R CMD SHLIB -o 'sourceCpp_4.so' 'test2.cpp' 
g++ -std=gnu++11 -I"/usr/share/R/include" -DNDEBUG -I../inst/include -fopenmp  -I"/home/aitap/R/x86_64-pc-linux-gnu-library/4.2/Rcpp/include" -I"/home/aitap/R/x86_64-pc-linux-gnu-library/4.2/RcppArmadillo/include" -I"/home/aitap/R/x86_64-pc-linux-gnu-library/4.2/RcppEigen/include" -I"/home/aitap/R/x86_64-pc-linux-gnu-library/4.2/RcppNumerical/include" -I"/home/aitap"    -fpic  -g -O2 -fdebug-prefix-map=/home/jranke/git/r-backports/buster/r-base-4.2.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2  -c test2.cpp -o test2.o
In file included from test2.cpp:6:
/home/aitap/R/x86_64-pc-linux-gnu-library/4.2/RcppArmadillo/include/RcppArmadillo.h:25:6: error: #error "The file 'Rcpp.h' should not be included. Please correct to include only 'RcppArmadillo.h'."
     #error "The file 'Rcpp.h' should not be included. Please correct to include only 'RcppArmadillo.h'."
      ^~~~~
```
This is on R-4.2.2 for Debian Buster, today's CRAN versions of all related packages. I might be missing something trivial about setting up the source file.

Regarding not rocking the boat, I suppose I could agree. Even if there there's nothing left in Armadillo to depend on the absence of the `NDEBUG` macro, this problem only shows up once a few years and has a clear workaround. Changing anything in a package depended upon by more than 1000 other packages only on CRAN should be weighted against the risk inherent in such change.

**Comment by eddelbuettel** [comment]
Ah, that is a test in `RcppArmadillo` which notices that `Rcpp.h` has been include (via `RcppNumerical`) so there goes my grand idea.  

A simple "not rocking the boat yet" change could be to protect the `#undef` via an outer `#if defined()` that would prevent it.

**Comment by eddelbuettel** [comment]
If you look at `RcppNumerical` (which is easy thanks to GitHub, consider eg [this search](https://github.com/search?q=repo%3Ayixuan%2FRcppNumerical%20%20assert&type=code)) you see that it carries three 'unprotective' `assert()` statements. 

That, together with `RcppArmadillo` indeed undefining `NDEBUG` (which I will think about some more) leads to the issue observed here.  It takes two to tango, as the expression goes, and that is the case here.  `RcppNumerical` is flying close to the fire by having `assert()` exposed _without ensuring `NDEBUG` is set_ and `RcppArmadillo` unsets it.  Boom.

The combination is rare which is why we don't generally see this.

**Comment by eddelbuettel** [comment]
But I am now leaning towards implementing your suggestion above to 'keep a marker' and to redefine at the end via new 'finalizing' header that the different entry points will include.

**Comment by aitap** [comment]
For what it's worth, I have fed `RcppArmadillo.h` to the preprocessor and dumped its state by running
```sh
g++ -DNDEBUG -E     -I /usr/share/R/include -I ~/R/x86_64-pc-linux-gnu-library/4.2/Rcpp/include -I ~/R/x86_64-pc-linux-gnu-library/4.2/RcppArmadillo/include ~/R/x86_64-pc-linux-gnu-library/4.2/RcppArmadillo/include/RcppArmadillo.h > RcppArmadillo.preprocessed
g++ -DNDEBUG -E -dM -I /usr/share/R/include -I ~/R/x86_64-pc-linux-gnu-library/4.2/Rcpp/include -I ~/R/x86_64-pc-linux-gnu-library/4.2/RcppArmadillo/include ~/R/x86_64-pc-linux-gnu-library/4.2/RcppArmadillo/include/RcppArmadillo.h > RcppArmadillo.symbols
```
...then repeated it after commenting out the `#undef NDEBUG` line and diffed the files. The only difference was the `NDEBUG` symbol being defined:

```
--- RcppArmadillo.symbols.orig  2022-11-15 13:42:18.636250969 +0300
+++ RcppArmadillo.symbols       2022-11-15 13:41:06.319966521 +0300
@@ -379,6 +379,7 @@
 #define SCNu8 "hhu"
 #define _SC_2_PBS_TRACK _SC_2_PBS_TRACK
 #define __attribute_used__ __attribute__ ((__used__))
+#define NDEBUG 1
 #define SCNxFAST64 __PRI64_PREFIX "x"
 #define CLOCK_REALTIME 0
 #define Rcpp_macros_interface_h
```

**Comment by eddelbuettel** [comment]
But re-read the comment in `RcppArmadilloConfigure.h`:  

>  `// R now defines NDEBUG which suppresses a number of useful Armadillo tests`

You need to do this in the `Armadillo` sources:

```sh
edd@rob:~/git/armadillo-code(11.4.x)$ ag -l assert include/ | wc -l
62
edd@rob:~/git/armadillo-code(11.4.x)$ 
```

**Comment by aitap** [comment]
Doesn't `RcppArmadillo.h` eventually include all Armadillo sources? `g++ -E ... RcppArmadillo.h` produces 12M of C++ code, including many bits of STL and quite a lot of files from `armadillo_bits/*`. I haven't checked that it's all of them, but it must be, given that Armadillo is template library: if something isn't included, there's no shared object to call it from.

While it's true that Armadillo source code contains the string `assert`, all of these calls end up in `armadillo_bits/debug.hpp`, where assertion errors are signaled by throwing exceptions instead of calling `::assert`. I can't find `<assert.h>` or `<cassert>` being included by Armadillo or RcppArmadillo.
Assuming that `#include <armadillo>` includes all of the Armadillo bits, here's a similar check done on the Armadillo sources:

```
armadillo-code/include$ diff -u <(g++ -E -x c++ armadillo) <(g++ -E -DNDEBUG -x c++ armadillo)
armadillo-code/include$ diff -u <(g++ -E -dM -x c++ armadillo) <(g++ -E -dM -DNDEBUG -x c++ armadillo)
--- /dev/fd/63  2022-11-15 16:20:59.823646565 +0300
+++ /dev/fd/62  2022-11-15 16:20:59.823646565 +0300
@@ -255,6 +255,7 @@
 #define arma_spbtrf spbtrf
 #define __SIZEOF_INT__ 4
 #define __attribute_used__ __attribute__ ((__used__))
+#define NDEBUG 1
 #define CLOCK_REALTIME 0
 #define __GCC_ATOMIC_CHAR16_T_LOCK_FREE 2
 #define _GLIBCXX_BEGIN_NAMESPACE_LDBL_OR_CXX11 _GLIBCXX_BEGIN_NAMESPACE_CXX11
```

Sorry for [making you spend more time on this than you might prefer to](https://xkcd.com/386/). There's probably more impactful bugs requiring your attention right now.

**Comment by eddelbuettel** [comment]
Your point is taken though: I cannot get `Armadillo` to actually abort on error (on a simple example).  Either it checks (good), or it (if overriden via `#define ARMA_NO_DEBUG` which is warned against) silently produces less useful output (as forced).

As you suggest, I think I stop here.  Maybe I just comment the old fragment that did the `#undef NDEBUG`.  It seems to serve no purpose now and has seen a (arguably rare) side effect we could do without.  Thanks for your continued help.
