### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by dahtah** [RcppCore/RcppArmadillo#177]
I'm getting a rather strange compilation error on Ubuntu 15.04 (R 3.2.3, gcc 4.9).
```
ccache g++-4.9 -std=c++11 -I/usr/share/R/include -DNDEBUG   -I"/localdata/barthesi/R/x86_64-pc-linux-gnu-library/3.2/Rcpp/include"  -I../inst/include -fopenmp -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -g -c RcppArmadillo.cpp -o RcppArmadillo.o
In file included from ../inst/include/armadillo:549:0,
                 from ../inst/include/RcppArmadilloForward.h:46,
                 from ../inst/include/RcppArmadillo.h:31,
                 from RcppArmadillo.cpp:22:
../inst/include/armadillo_bits/eop_core_meat.hpp:305:139: error: stray ‘#’ in program
       arma_applier_2_mp(=);
```                                   
I've checked the file and it looks fine. Any idea?

**Comment by eddelbuettel** [comment]
Do you have a full / reproducible example?  I think _many_ people still regularly use older systems as _e.g._ Travis defaults to 14.04 and g++ 4.8.   So your pick should be find.    Fewer people may use R 3.2.3 though.

**Comment by eddelbuettel** [comment]
It is something on your end. I just fired up an Ubuntu 14.04 VM (which has R 3.0.2) and installed RcppArmadillo just fine.  Both the current CRAN version and what we have in master on GitHub and which may be on CRAN within a day or two.

**Comment by dahtah** [comment]
I've just checked and it compiles with clang. I suppose I'll file this under "weird gcc bug", then. Thanks!

**Comment by eddelbuettel** [comment]
I am sure something else must be going on.   

Maybe on OpenMP interaction?  Try without `ccache` and use different optimization levels.

Also, 15.04 stopped being supported a loooong time ago.  Maybe move to 16.04 at least?  I'm happy on 17.04.

**Comment by eddelbuettel** [comment]
The error comes from [this block](https://github.com/cran/RcppArmadillo/blob/ce8dd7e68b9d4708379ae6acb3051b104d56e3fc/inst/include/armadillo_bits/eop_core_meat.hpp#L303-L310) and _is_ conditional on `use_mp`.  

Can you copy and paste the few relevant line from the `configure` output, please?  Maybe Armadillo thinks it has OpenMP when it doesn't?  Maybe your troubles go away if you opt out of OpenMP?  

It would help us to understand how we got there in the first place. I have not seen this otherwise, and I am on Ubuntu/Debian systems _a lot_.

**Comment by dahtah** [comment]
Disabling ccache solves the problem. Not sure what's going on here. configure finds OpenMP (as it should, it's available): 
```
checking for OpenMP... found
configure: WARNING: "Setting $(SHLIB_OPENMP_CXXFLAGS)"
```



I know the system's old and I should upgrade, but I'm dependent on our sysadmins for that, and most days I have something more urgent to do.

**Comment by eddelbuettel** [comment]
I am really glad we found this.  I still don't understand it -- I use `ccache` all the time myself for all R builds (and had been planning a blog post on it) and have never been "bitten" by it either.

Very strange.  But at least a) you're over it and b) we don't seem to have an issue in RcppArmadillo.

**Comment by dahtah** [comment]
Thanks for your help Dirk!

**Comment by eddelbuettel** [comment]
Pas de quoi.  But do upgrade. It is wat more efficient _for me_ if you "waste your time" at that end ;-)

**Comment by cworsnup13** [comment]
I'm facing this same issue @eddelbuettel 
Issue
```> install.packages('RcppArmadillo')
Installing package into ‘/home/uber/R/x86_64-pc-linux-gnu-library/3.3’
(as ‘lib’ is unspecified)
trying URL 'https://cloud.r-project.org/src/contrib/RcppArmadillo_0.8.100.1.0.tar.gz'
Content type 'unknown' length 1312598 bytes (1.3 MB)
==================================================
downloaded 1.3 MB

* installing *source* package ‘RcppArmadillo’ ...
** package ‘RcppArmadillo’ successfully unpacked and MD5 sums checked
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking how to run the C++ preprocessor... g++ -E
checking whether we are using the GNU C++ compiler... (cached) yes
checking whether g++ accepts -g... (cached) yes
checking whether g++ version is sufficient... (4.9.2) yes
checking LAPACK_LIBS... system LAPACK found
checking for macOS... not found as on Linux
checking for OpenMP... found
configure: creating ./config.status
config.status: creating inst/include/RcppArmadilloConfigGenerated.h
config.status: creating src/Makevars
** libs
g++ -std=c++11 -I/usr/share/R/include -DNDEBUG   -I"/home/uber/R/x86_64-pc-linux-gnu-library/3.3/Rcpp/include"  -I../inst/include -fopenmp -fpic  -g -O2 -fstack-protector-strong -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -g -c RcppArmadillo.cpp -o RcppArmadillo.o
In file included from ../inst/include/armadillo:552:0,
                 from ../inst/include/RcppArmadilloForward.h:46,
                 from ../inst/include/RcppArmadillo.h:31,
                 from RcppArmadillo.cpp:22:
../inst/include/armadillo_bits/eop_core_meat.hpp:305:139: error: stray ‘#’ in program
       arma_applier_2_mp(=);
                                                                                                                                           ^
In file included from ../inst/include/armadillo:552:0,
                 from ../inst/include/RcppArmadilloForward.h:46,
                 from ../inst/include/RcppArmadillo.h:31,
                 from RcppArmadillo.cpp:22:
../inst/include/armadillo_bits/eop_core_meat.hpp:305:123: error: stray ‘#’ in program
       arma_applier_2_mp(=);
```

Versions
```
$ g++ -v
Using built-in specs.
COLLECT_GCC=/usr/bin/g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/4.9/lto-wrapper
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Debian 4.9.2-10' --with-bugurl=file:///usr/share/doc/gcc-4.9/README.Bugs --enable-languages=c,c++,java,go,d,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.9 --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.9 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --disable-vtable-verify --enable-plugin --with-system-zlib --disable-browser-plugin --enable-java-awt=gtk --enable-gtk-cairo --with-java-home=/usr/lib/jvm/java-1.5.0-gcj-4.9-amd64/jre --enable-java-home --with-jvm-root-dir=/usr/lib/jvm/java-1.5.0-gcj-4.9-amd64 --with-jvm-jar-dir=/usr/lib/jvm-exports/java-1.5.0-gcj-4.9-amd64 --with-arch-directory=amd64 --with-ecj-jar=/usr/share/java/eclipse-ecj.jar --enable-objc-gc --enable-multiarch --with-arch-32=i586 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 4.9.2 (Debian 4.9.2-10)
```
OS
```
$ cat /etc/*release*
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=debian
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
R
```
R version 3.3.3 (2017-03-06) -- "Another Canoe"
```

**Comment by eddelbuettel** [comment]
Same problem as above:  Armadillo thinks you should have OpenMP.  Do you?   `dpkg -s libgomp1` ?

**Comment by cworsnup13** [comment]
```
$ dpkg -s libgomp1
Package: libgomp1
Status: install ok installed
Priority: optional
Section: libs
Installed-Size: 123
Maintainer: Debian GCC Maintainers <debian-gcc@lists.debian.org>
Architecture: amd64
Multi-Arch: same
Source: gcc-4.9
Version: 4.9.2-10
Depends: gcc-4.9-base (= 4.9.2-10), libc6 (>= 2.17)
Pre-Depends: multiarch-support
Breaks: gcc-4.3 (<< 4.3.6-1), gcc-4.4 (<< 4.4.6-4), gcc-4.5 (<< 4.5.3-2)
Description: GCC OpenMP (GOMP) support library
 GOMP is an implementation of OpenMP for the C, C++, and Fortran compilers
 in the GNU Compiler Collection.
Homepage: http://gcc.gnu.org/
```

**Comment by eddelbuettel** [comment]
So not that.  What else is going wrong?  I can't tell, and it works at CRAN.

The error message is clear:  line 305 in file `eOp_meat.hpp` is having issues. Try to see what it is, and try to figure out why it is unhappy.   [Works everywhere else (modulo one Fedora issue with the vignette)](https://cloud.r-project.org/web/checks/check_results_RcppArmadillo.html).

**Comment by cworsnup13** [comment]
okay, I'll see what I can checkout here. But it is only this version release that has caused this issue. So for the meantime I'm going to install the older rcpparmadillo since that works. 

I'll see if I can help with this bug by digging in on this specific OS

**Comment by eddelbuettel** [comment]
You can (and maybe should) use the new version, you can override the "is OpenMP on" setting by flipping this switch at the end of this block: 
https://github.com/RcppCore/RcppArmadillo/blob/master/inst/include/RcppArmadilloConfig.h#L96-L120

Just add a line with `#define ARMA_DONT_USE_OPENMP 1` and OpenMp will be suppressed.  

That said, we need to know what is wrong with your setup. You _should_ have it.

**Comment by conradsnicta** [comment]
@eddelbuettel - I suggest not to enable OpenMP in RcppArmadillo if version of gcc < 5.0.  This means that gcc 4.6, 4.7, 4.8, 4.9 are all "bad" (yep, this includes 4.8 and 4.9).

To summarise the long story:
(1) general use of C++11 is okay with gcc 4.8 and later versions.
(2) don't use OpenMP if version of gcc is lower than 5.

Long story:
Armadillo requires a properly conforming C++11 compiler in order to use OpenMP.  Versions of gcc < 5 have incomplete and/or buggy support for C++11.  While gcc 4.8 and 4.9 were advertised as supporting C++11, in reality their C++11 support has a few bugs.  I suspect that in a few contexts they are not properly handling certain forms of the pragma keyword (#pragma vs the newer _Pragma).  The newer form is used by Armadillo to parallelise loops via OpenMP.  (Using the old form is not doable - another long story).

Ubuntu 15.10 and later versions (including 16.04 LTS) use gcc 5.x or better, meaning that gcc 4.8 and 4.9 in the Ubuntu world are ancient history at this point.  While RHEL 7 uses gcc 4.8 as its baseline compiler, Red Hat provides more updated versions of gcc through addons (I believe the addons are called Software Collections). I don't know the state of gcc in Debian, though I suspect most people don't use the ancient "stable" branch and instead use the "testing" branch (which has a recent enough compiler). Recent releases of Fedora are using gcc 7, so there are no problems there.

Note that use of other C++11 features in Armadillo appears to work perfectly fine with gcc 4.8 and 4.9 (ie. other than the problem with OpenMP).

**Comment by eddelbuettel** [comment]
Yeah, I had case with g++ 4.9.* where C++11 was there "well enough" for the compiler but not the library.  Will rejig and condition on g++ 5.* as you suggest here, and as I had just surmised over in the other thread.

Any idea about good/bad clang versions?

**Comment by conradsnicta** [comment]
Relevant bug report in gcc: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=57580

Don't know about clang.

**Comment by eddelbuettel** [comment]
We can accomodate because I already have a crude, but reliable setup used (initially for another package) for over a decase, see [here for RcppArmadillo](https://github.com/RcppCore/RcppArmadillo/blob/dee02abec9aed7935971886699d0d5c1b6eaa72d/configure.ac#L30-L51) .

I guess I will just default to 'nope' for OpenMP but turn it on if and only if we see a recent enough `g++`.  The situation on macOS is so dire that it is best to turn it off too, and if someone insists on clang under Linux they get to tweak it themselves.  For a "good enough" `g++` we can play.

**Comment by eddelbuettel** [comment]
If you install the GitHub-release version 0.8.200.1.1, this issue should be addressed. Do either

```r
drat::addRepo("RcppCore")             # RcppCore drat repo known for rest of session
install.packages("RcppArmadillo")
```

or 

```r
install.packages("RcppArmadillo", repos="https://RcppCore.github.io/drat")
```
