### ISSUE TITLE
RD test failure with reduced LAPACK

### ISSUE THREAD

**Issue by eddelbuettel** [RcppCore/RcppArmadillo#213]
@kthohr I get this on R-devel with an embedded LAPACK on Ubuntu 17.10:

```
--------------------------- 
Test file: /home/edd/git/rcpparmadillo/RcppArmadillo.Rcheck/RcppArmadillo/unitTests/runit.Rlapack.R 
.setUp (before test.Rlapack): ERROR !! 
Error executing .setUp before test.Rlapack : Error in dyn.load("/tmp/Rtmp0RSN4J/sourceCpp-x86_64-pc-linux-gnu-0.12.16/sourcecpp_60e72fa3cfdb/sourceCpp_8.so") : 
  unable to load shared object '/tmp/Rtmp0RSN4J/sourceCpp-x86_64-pc-linux-gnu-0.12.16/sourcecpp_60e72fa3cfdb/sourceCpp_8.so':
  /tmp/Rtmp0RSN4J/sourceCpp-x86_64-pc-linux-gnu-0.12.16/sourcecpp_60e72fa3cfdb/sourceCpp_8.so: undefined symbol: zgbsv_
--------------------------- 
```

I presume this passed on your macOS box?

**Comment by kthohr** [comment]
Hmm... `zgbsv` is only used with band matrices (and is indeed missing on Rlapack). I will investigate why this is being called by my tests.

**Comment by kthohr** [comment]
I just ran the tests on a Windows machine with Rlapack and everything passed. 
```
Executing test function test.Rlapack  ...  done successfully.
```
Just to be clear: that R-devel is linking with Rlapack? If so, the crippled_lapack switch must be missing.

**Comment by kthohr** [comment]
I think this is the culprit: https://github.com/RcppCore/RcppArmadillo/blob/master/configure.ac#L85

The crippled_lapack switch needs to be enabled for _all_ Rlapack cases.

**Comment by eddelbuettel** [comment]
Doh. I think you are spot on.

**Comment by kthohr** [comment]
Actually this PR might fix @baptiste 's issue, too.

**Comment by eddelbuettel** [comment]
But only platforms that do not use the embedded Rlapack -- on those he would have to add the lapack routine called by Armadillo in his package to fill-in.  Or am I missing something here?

**Comment by kthohr** [comment]
From  @baptiste 's description, the Linux build on CRAN failed due to a generic `solve()` call when the inputs were complex-valued. This is also what my unit test was doing.

From my understanding of the Armadillo code, `solve()` will alternate between different solvers depending on the properties of the input matrices, which includes the band matrix case, but this special case isn't required to return a solution (it's just used to exploit a simplified structure where available). `ARMA_CRIPPLED_LAPACK` should rule out these routines:

https://github.com/conradsnicta/armadillo-code/blob/unstable/include/armadillo_bits/auxlib_meat.hpp#L3755

My guess is that the configure script saw an R version > 3.3.0 and did not set `ARMA_CRIPPLED_LAPACK`, so the band matrix routines were not removed.

**Comment by baptiste** [comment]
This is also my understanding, as was discussed at length on the mailing
list. Thank you for the work, and I believe it should fix such issues much
more reliably than testing for OS and R version, which (especially on CRAN)
are not the relevant variables to enforce the crippled flag. My package was
archived by CRAN following this failure and will not automatically rebuild;
I will not have time in the near future to work on this and push a new
version but I appreciate everyone's efforts to improve the global
situation. The R-devel discussion also suggests that a full Lapack could
potentially be included, especially if someone were to submit a patch; it
seems to be more of a case of not having resources to provide a careful
implementation for the remaining wrappers than any technical or
philosophical reservations.

Regards,

baptiste
