### ISSUE TITLE
installer on Red Hat ends up with ARMA_CRIPPLED_LAPACK being set

### ISSUE THREAD

**Issue by conradsnicta** [RcppCore/RcppArmadillo#286]
Installing RcppArmadillo in R 3.6.0 on a Linux box seems partly broken.  The installer thinks it's on macOS, which is problematic.

This results in the undesirable `#define ARMA_CRIPPLED_LAPACK 1` being set in 
`RcppArmadilloConfigGenerated.h`, which unnecessarily reduces functionality.

The linux box has full standard LAPACK (not the partial one shipped with R). It also has OpenBLAS with full LAPACK.  Details below.

Output from running R and installing RcppArmadillo:

```
R version 3.6.0 (2019-04-26) -- "Planting of a Tree"

Copyright (C) 2019 The R Foundation for Statistical Computing
Platform: x86_64-redhat-linux-gnu (64-bit)
...
> install.packages("RcppArmadillo")
...
trying URL 'https://cran.ms.unimelb.edu.au/src/contrib/RcppArmadillo_0.9.850.1.0.tar.gz'
Content type 'application/octet-stream' length 1381269 bytes (1.3 MB)
==================================================
downloaded 1.3 MB
...
checking whether g++ version is sufficient... yes, with OpenMP as version 9.2.1
checking for macOS... checking LAPACK_LIBS... R-supplied partial LAPACK found
configure: WARNING: Some complex-valued LAPACK functions may not be available
checking for OpenMP... found and suitable
```

Looking at the installed RcppArmadillo, we have:
```
> cat R/x86_64-redhat-linux-gnu-library/3.6/RcppArmadillo/include/RcppArmadilloConfigGenerated.h
...
#ifndef ARMA_CRIPPLED_LAPACK
// value on next line may be changed between #undef and #define by the configure script
#define ARMA_CRIPPLED_LAPACK 1
#endif
...
```

The Linux box is Fedora 30, with the following packages installed:
```
lapack-devel-3.8.0-12.fc30.x86_64
blas-devel-3.8.0-12.fc30.x86_64
openblas-devel-0.3.7-1.fc30.x86_64
R-3.6.0-1.fc30.x86_64
gcc-9.2.1-1.fc30.x86_64
gcc-c++-9.2.1-1.fc30.x86_64
clang-8.0.0-3.fc30.x86_64
```

Maybe the installer thinks this is macOS because both gcc and clang are present ?

**Comment by conradsnicta** [comment]
Same problem occurs when R is updated from 3.6.0 to 3.6.2.

**Comment by rstub** [comment]
This is the interesting part

```
checking LAPACK_LIBS... R-supplied partial LAPACK found
```
which triggers `#define ARMA_CRIPPLED_LAPACK 1`. What is the output of the folowing commands?

```
R CMD config LAPACK_LIBS
ls -l $(R RHOME)/lib
```

**Comment by eddelbuettel** [comment]
What is "on a Linux"? Does the OS have a name?  Can you make this reproducible? Are there Docjer containers? Can you may take a stab a correcting `configure.ac` so that it passes?

**Comment by eddelbuettel** [comment]
So it's Red Hat. Whose R is fsking terrible. Had it at work once or twice, luckily not right now.

It also seems to have issue with _line breaks_.  You simple misread / where shown a bad one in 

```
checking whether g++ version is sufficient... yes, with OpenMP as version 9.2.1
checking for macOS... checking LAPACK_LIBS... R-supplied partial LAPACK found
configure: WARNING: Some complex-valued LAPACK functions may not be available
checking for OpenMP... found and suitable
```

Here `checking LAPACK_LIBS` comes after the macOS check, and if there is a bug it may be that we mix a line-end in the not-found case.   As for 'R-supplied partial LAPACK found':  Yup.

And that is _not us_. It is an issue with the way R builds, and R is built on RedHat, and not something we can adjust or work around.  We just cannot.  See [this detailed R manual](https://cran.r-project.org/doc/manuals/r-release/R-admin.html) (which also ships with R like the other manuals) for more.

**Comment by eddelbuettel** [comment]
As for the missing new-line, the macOS check is this:

```sh
## Check for Apple LLVM

AC_MSG_CHECKING([for macOS])
RSysinfoName=$("${R_HOME}/bin/Rscript" --vanilla -e 'cat(Sys.info()[["sysname"]])')

if test x"${RSysinfoName}" = x"Darwin"; then
    AC_MSG_RESULT([found])
    AC_MSG_CHECKING([for macOS Apple compiler])

    apple_compiler=$($CXX --version 2>&1 | grep -i -c -e 'apple llvm')

    if test x"${apple_compiler}" = x"1"; then
        AC_MSG_RESULT([found])
        AC_MSG_WARN([OpenMP unavailable and turned off.])
        can_use_openmp="no"
    else
        AC_MSG_RESULT([not found])
        AC_MSG_CHECKING([for clang compiler])
        clang_compiler=$($CXX --version 2>&1 | grep -i -c -e 'clang ')

        if test x"${clang_compiler}" = x"1"; then
            AC_MSG_RESULT([found])
            AC_MSG_CHECKING([for OpenMP compatible version of clang])
            clang_version=$(${CXX} -v 2>&1 | awk '/^.*clang version/ {print $3}')

            case ${clang_version} in
                4.*|5.*|6.*|7.*|8.*|9.*|10.*|11.*)
                    AC_MSG_RESULT([found and suitable])
                    can_use_openmp="yes"
                ;;
                *)
                    AC_MSG_RESULT([not found])
                    AC_MSG_WARN([OpenMP unavailable and turned off.])
                    can_use_openmp="no"
                ;;
            esac
        else
            AC_MSG_RESULT([not found])
            AC_MSG_WARN([unsupported macOS build detected; if anything breaks, you keep the pieces.])
        fi
    fi
fi

```

and contributed by @coatless .  I now see that I show the same error on my Linux so it is simply "buggy" (well, too big a word) or "mac centric" in not providing a newline in the non-macOS case.  

But it mislead you so I will try to fix this.

**Comment by eddelbuettel** [comment]
Easy enough to fix the cosmetics here

```diff
@@ -103,6 +103,8 @@ if test x"${RSysinfoName}" = x"Darwin"; then
             AC_MSG_WARN([unsupported macOS build detected; if anything breaks, you keep the pieces.])
         fi
     fi
+else
+    AC_MSG_RESULT([no])
 fi
 
 ## Check for suitable LAPACK_LIBS

```

leads to 

```sh
edd@rob:~/git/rcpparmadillo(master)$ ./configure 
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether ccache g++ accepts -g... yes
checking how to run the C++ preprocessor... ccache g++ -E
checking whether we are using the GNU C++ compiler... (cached) yes
checking whether ccache g++ accepts -g... (cached) yes
checking whether g++ version is sufficient... yes, with OpenMP as version 9.2.1
checking for macOS... no
checking LAPACK_LIBS... system LAPACK found
checking for OpenMP... found and suitable
configure: creating ./config.status
config.status: creating inst/include/RcppArmadilloConfigGenerated.h
config.status: creating src/Makevars
edd@rob:~/git/rcpparmadillo(master)$ 
```

which is preferable. I apologize for overlooking this earlier.

This is, however, not the issue at hand for which you (or someone else) has to talk to RedHat.

**Comment by conradsnicta** [comment]
This is indeed 2 separate issues, as listed below. This seems to be also a can of worms, possibly demonstrating an important limitation / lack of functionality in Fedora and/or Red Hat.

The 2 separate issues are:
1. Minor issue of the lack of newline in the configuration output, as mentioned by @eddelbuettel  in comment https://github.com/RcppCore/RcppArmadillo/issues/286#issuecomment-586991030.

2. Major issue of a bug in the Fedora (and Red Hat?) package for R, where the R supplied partial/borked LAPACK is used instead of using the proper system-level LAPACK. Really not sure what led to this brilliant decision.

Following the suggestion by @rstub in https://github.com/RcppCore/RcppArmadillo/issues/286#issuecomment-586958618
```
> R CMD config LAPACK_LIBS
-L/usr/lib64/R/lib -lRlapack

> ls /usr/lib64/R/lib
libRblas.so
libRlapack.so
libRrefblas.so
libR.so
```
This sillyness doesn't end here though.  We have this lovely gem:
```
> rpm -q --whatprovides /usr/lib64/R/lib/libRblas.so
openblas-Rblas-0.3.7-1.fc30.x86_64

> rpm -qi openblas-Rblas-0.3.7-1.fc30.x86_64
Name        : openblas-Rblas
Version     : 0.3.7
...
Summary     : A version of OpenBLAS for R to use as libRblas
```

So instead of using the system level OpenBLAS, there is a completely separate and redundant OpenBLAS package specifically for R. I bet that this packing of OpenBLAS actually has full LAPACK inside.

Clearly there are the obvious questions:
  * why use the R-supplied partial/borked LAPACK on a system which has full LAPACK ?
  * why completely repackage OpenBLAS ?

I think there might be an even bigger issue here:
  * does Fedora and/or Red Hat lack a technique for changing what liblapack.so and libblas.so point to, in order to allow a system-wide change of the implementation of lapack and blas?  
Example:  when OpenBLAS is installed, make libblas.so point to libopenblas.so

If I recall correctly, Debian/Ubuntu have the so-called "alternatives" mechanism to handle this.

**Comment by eddelbuettel** [comment]
@Conrad:

Point one is already fixed.  It now shows better behavior as in the snippet at the bottom.

Point two is well understood, and beyond your and my control.  It is a combination of what R offers (and, frankly, preferred for many years as they found numerical issues in some LAPACK / BLAS version shipped maybe a decade or so ago; these habits then change slowly if at all) and what RHEL elects to use.  Which is, to the best I can tell, infuriatingly bad.  I have spent a good decade plus professionally on Debian/Ubuntu machines which are setup better in their excellent 'alternatives' use of BLAS and LAPACK which we had since the late 1990s (!!).   I as R maintainer simply profit from it and have to do nothing extra.  I also spent some time more recently with CentOS and it is simply much worse (specifically for R).  So the point is: how can we get some more sensible choices enacted at RedHat?   CCing @Enchufa2 who knows his way around R and Rcpp, and who knows some people there.  Maybe he can help.

I am happy to keep this issue 'open' for means of a focussed discussion, but I will 'close' it it is strictly not a code bug in RcppArmadillo.  The package does the best it can given the circumstances (and added the missing newline as shown below).


```sh
edd@rob:~/git/rcpparmadillo(master)$ ./configure                ## as of current master 
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether ccache g++ accepts -g... yes
checking how to run the C++ preprocessor... ccache g++ -E
checking whether we are using the GNU C++ compiler... (cached) yes
checking whether ccache g++ accepts -g... (cached) yes
checking whether g++ version is sufficient... yes, with OpenMP as version 9.2.1
checking for macOS... no
checking LAPACK_LIBS... system LAPACK found
checking for OpenMP... found and suitable
configure: creating ./config.status
config.status: creating inst/include/RcppArmadilloConfigGenerated.h
config.status: creating src/Makevars
edd@rob:~/git/rcpparmadillo(master)$
```

**Comment by conradsnicta** [comment]
I may add a define like `ARMA_NO_CRIPPLED_LAPACK` which can be used to optionally override `ARMA_CRIPPLED_LAPACK` in Armadillo.

This may help with testing the state of the bizarre `openblas-Rblas` package mentioned in https://github.com/RcppCore/RcppArmadillo/issues/286#issuecomment-587246152, and/or allow users override the silliness of the borked R packaging on Fedora / Red Hat.

**Comment by eddelbuettel** [comment]
Hm, how would it/could it help? I essence "we" are an R package, and we build, compile, link, ... via (in essence) invocation of (the equivalent of) shell commands `R CMD xyz` where xyz is `build`, `COMPILE`. ... and so on.  

For its settings, look into the file indicated by `R.home("etc/Makeconf")` (for me: `/usr/lib/R/etc/Makeconf` and also `/etc/R/Makeconf` by a in-the-distro convenience copy and softlink).  It has (again, quoting mine) `BLAS_LIBS` and `LAPACK_LIBS` set.  And we (as an R package) cannot override that. Same with the other settings in there.  We can _add_ a few things _per package_ in `PKG_CXXFLAGS` etc, but we _cannot undo or override_ the settings in the file.  That has always been that way, for better (predictable outcomes) or worse (a certain lack of flexibility even for debug and optimization flags, those just get added again 'to the right').

**Comment by spotrh** [comment]
Hi Dirk. I maintain the R packages for Fedora and EPEL (addons for RHEL/CentOS). I also maintain LAPACK in Fedora (but not OpenBLAS).

The system LAPACK in EL-5,6,7 is in a poor state. I've filed bugs to try to get them fixed, but there has been no interest in resolving those issues (and what happens in RHEL is entirely out of my control). The LAPACK in EL-8 should be fine however.

As far as Fedora goes, there is no good reason why it cannot use the system LAPACK/blas (from openblas), and in fact, I thought it was doing so, but I had a conditional incorrect in the spec file (RPM equivalent of rules). I'm testing that fix now to make sure that Fedora (and EL-8) builds no longer generate Rlapack.so or Rblas.so.

Thanks for bringing this to my attention.

**Comment by eddelbuettel** [comment]
Hi @spotrh and thanks for reaching out!  Happy to help here, or off-line at my usual debian.org handle.

We got lucky as we had Camm establish a superbly engineered solution over twenty years ago.  We have been riding that ever since.  I once built an entire timing and comparison framework around 'live switching' of BLAS/LAPACK (traces of that in a now dated paper / write up [here in the R package for it](https://cloud.r-project.org/web/packages/gcbd/vignettes/gcbd.pdf).  I also threw in an informal / "not published, just on GitHub" [script to turn the MKL](https://github.com/eddelbuettel/mkl4deb) on (now that Intel is nice to us on licenses and reuse), that garnered over a 100 GitHub stars with little publicity apart from one blog post.  

I also have some ~20 years of shipping R for Debian and have a few little value added files, script, settings in its build.  The repo is a bit of a mess (did I mention 20+ years? :grinning: ) but you can take a look at the salsa repo https://salsa.debian.org/edd/r-base

Maybe you can experiment with a bit of change, and then maybe get Tom to buy in for the RHEL/CentOS package.

**Comment by spotrh** [comment]
Your repo was the first thing I checked to ensure I had proper flags while fixing this up. :)
The Fedora R spec also contains large amounts of "fun" and "ugly", I believe I took it over in 2005.

The new build I just did locally links to libopenblas.so.0 and no longer generates libRlapack/libRblas. 

Fixing RHEL/CentOS 5-6-7 is a hopeless cause at this point, for a number of reasons, but most notably, because the gcc on them is too old to have the proper C++ support that R wants. Folks trying to use R on those older EL targets should really consider moving to EL-8.

**Comment by Enchufa2** [comment]
Thanks, @spotrh, for jumping in so quickly. I'm sure you don't need any help, but still, if I can do something, apart from summoning you, some testing or whatever, you have my email and I'll be more than glad to help.

@conradsnicta Do you know the [Chesterton's fence](https://en.wikipedia.org/wiki/Wikipedia:Chesterton%27s_fence)? It's evident from your comments that you don't. Here, the current status of R in Fedora/RH/CentOS is the _fence_, and you know _nothing_ about it. So before throwing up all that stuff and big words, you should politely ask for the details about why the _fence_ is there, because people in charge of maintaining an entire OS are not stupid, and usually there are some good reasons for that _fence_ to be there, and you may even end up learning something. And when you do know the details, if the original reasons are not there anymore, then you can politely propose a change. Otherwise, the attitude you showed in this thread won't bring you much help in any open source project.

**Comment by eddelbuettel** [comment]
I propose we keeps things civil and remove the entire second paragraph in the last comment.

**Comment by spotrh** [comment]
Just to confirm, with my local changes, RcppArmadillo correctly finds and uses system LAPACK (via openblas):

``
>  install.packages("RcppArmadillo")
Installing package into ‘/home/spot/R/x86_64-redhat-linux-gnu-library/3.6’
(as ‘lib’ is unspecified)
--- Please select a CRAN mirror for use in this session ---
trying URL 'https://mirrors.nics.utk.edu/cran/src/contrib/RcppArmadillo_0.9.850.1.0.tar.gz'
Content type 'application/x-gzip' length 1381269 bytes (1.3 MB)
==================================================
downloaded 1.3 MB

* installing *source* package ‘RcppArmadillo’ ...
** package ‘RcppArmadillo’ successfully unpacked and MD5 sums checked
** using staged installation
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++ -m64 -std=gnu++11 accepts -g... yes
checking how to run the C++ preprocessor... g++ -m64 -std=gnu++11 -E
checking whether we are using the GNU C++ compiler... (cached) yes
checking whether g++ -m64 -std=gnu++11 accepts -g... (cached) yes
checking whether g++ version is sufficient... yes, with OpenMP as version 10.0.1
checking for macOS... checking LAPACK_LIBS... system LAPACK found
checking for OpenMP... found and suitable
configure: creating ./config.status
config.status: creating inst/include/RcppArmadilloConfigGenerated.h
config.status: creating src/Makevars

I'm off to make proper R updates for Fedora and EPEL (as well as for the 7 R module packages that picked up a dependency on libRlapack.so). Please do not hesitate to let me know (either by tagging me on github, filing a bug, or email) if you see anything else inappropriate in the Red Hat R universe.

**Comment by eddelbuettel** [comment]
Local changes ... to your R build, I presume?

**Comment by spotrh** [comment]
Yes, sorry, that was ambiguous. No code changes were necessary to RcppArmadillo. :)

**Comment by conradsnicta** [comment]
@spotrh Thanks for looking into this.

Does Fedora currently handle (or allow) changing the implementation of LAPACK on the fly?  For example, is it possible to change `/usr/lib64/liblapack.so` so it points to, say, `/usr/lib64/libopenblaso.so` or `/usr/lib64/libopenblasp.so` ?

A quick search turns up [this page](https://fedoraproject.org/wiki/PackagingDrafts:BLAS_LAPACK) on the Fedora site, but it seems to be in draft form only.

There is also the "[OpenBLAs as default BLAS](https://fedoraproject.org/wiki/Changes/OpenBLAS_as_default_BLAS)" proposal for F32, but this doesn't seem to allow doing on-the-fly changes to BLAS.

**Comment by spotrh** [comment]
I do not believe Fedora has any infrastructure at the moment to handle/allow/enable changing the system default for LAPACK/BLAS. I would be supportive of an effort to create that infrastructure (and yes, using alternatives would seem to be a logical way).

It does seem that there is some initial complexity around openblas, specifically in the R case, where when we build R against it (libopenblas.so), it then passes -lopenblas to CRAN module builds. I'm not sure if there is a clever way to build R such that it gets the advantages of openblas (namely, the included lapack), but also enables a mechanism for the user to swap it out without breaking things.

It seems clear that there is room for improvement here, and any concrete suggestions would be appreciated.

**Comment by eddelbuettel** [comment]
At Debian we found it works well when you 

a) tell R at configure and build time to use the BLAS and LAPACK interface which ends with externally linked lapack and blas (and those external link instructions "written down" in `Makeconf`) as opposed to the 'R-prefixed' ones you get by default and which @conradsnicta found in your CentOS/RHEL builds.  I should note that is of course what (at least parts of) R Core want: Prof Ripley was often adamant about buggy BLAS etc pp and preferred the shipped-with-R subset which had given Conrad and me fits in the past as it lacked some complex-valued routines Armadillo can use

b) have libraries conforming to this scheme because then you can use an alternative mechanism which for us is/was refBlas, OpenBLAS (Goto in the past), Atlas and more (like the external MKL ones). I am a little removed from the process but AFAIK a rework is considered to get BLIS in and whatnot.

Another nice part of the alternatives scheme is that it works for other packages and libraries using BLAS/LAPACK too -- I once was the maintainer for GNU Octave and used it there too (in the 1990s).

**Comment by spotrh** [comment]
We definitely use alternatives in other places in Fedora, so it wouldn't be a foreign change.

On R, I'm currently passing these to configure:
    --with-lapack \
    --with-blas \

When openblas is in the BuildRoot, R ends up being linked to libopenblas.so. Are you suggesting that we should put the reference LAPACK/BLAS in the BuildRoot instead, so that R ends up linked to liblapack.so and libblas.so (and then possibly swapping the system default using alternatives?)

Just making sure I understand properly. Thanks in advance.

**Comment by eddelbuettel** [comment]
See debian/rules for the most explicit statement -- that's why I pointed to salsa.debian.org earlier.

**Comment by spotrh** [comment]
So yes, Debian is building against the reference LAPACK and BLAS. Thanks. My brain doesn't parse debian packaging logic so I had to find the answer in debian/control.

**Comment by eddelbuettel** [comment]
No! Yes! Both!

The statement is not correct, necessarily.  We don't "build against refblas".   We have a build dependency on a _virtual package_ and that dependency can be satisfied by refblas, openblas, atlas, ... .  So while you may see a log with refblas, or experience a build with refblas you could _equally well have seen one with openblas_.

The critical point is that _none of these become depends_.  The virtual interface is the depends.  Any of the candidate provides can fulfil this virtual dependency.

These detail matter.  I am in a bit of rush otherwise.  Hope this helps.

**Comment by eddelbuettel** [comment]
`debian/control` has multiple entries.  The Build-Depends is (per my last comment) just one that is feasible.  I also tell the `r-base-dev` package (which helps to pull in things needed when building R or R packages) via a Depends: ... For example in `debian/control` I have `r-base-dev` with a depends 

```
    libblas-dev | libatlas-base-dev, 
    liblapack-dev | libatlas-base-dev
```

which nudges towards the Atlas variants.  The first is the virtual, the second is one possible actual.

Most importantly, see what r-base-core ends up with.  Easiest view the web at https://packages.debian.org/sid/r-base-core and I will just screen-shot:

![image](https://user-images.githubusercontent.com/673121/74866430-7d04ab80-5318-11ea-83df-312de933d220.png)

Ditto for lapack:

![image](https://user-images.githubusercontent.com/673121/74866498-94dc2f80-5318-11ea-989f-c2d717578ced.png)

**Comment by eddelbuettel** [comment]
It is a wee-bit complicated to explain :)   

But key it a) works great and b) hasn't required packaging changes.

**Comment by Enchufa2** [comment]
We could copy the mechanism that sendmail, postfix and others use: they all declare `Provides: smptdaemon`, but there's no `smptdaemon`, that's just something other packages require to be able to send emails.

**Comment by eddelbuettel** [comment]
That is a start but you need (as I recall) more as you e.g. also need to filter `ldd` output for the packages to bring the depends on the virtual package back in when you see a concrete one linked.

**Comment by Enchufa2** [comment]
Yes, [there are macros](https://docs.fedoraproject.org/en-US/packaging-guidelines/AutoProvidesAndRequiresFiltering/) to filter automatic requires.

**Comment by conradsnicta** [comment]
CC: @opoplawski - appears directly related to your draft Fedora packaging proposal: https://fedoraproject.org/wiki/PackagingDrafts:BLAS_LAPACK

@lupinix - related to your Fedora proposal on system-wide use of OpenBLAS: https://fedoraproject.org/wiki/Changes/OpenBLAS_as_default_BLAS

**Comment by opoplawski** [comment]
My draft was never fully realized (it has issues that have not been addressed).  Fedora has mostly standardized on OpenBLAS at this point as noted.

**Comment by Enchufa2** [comment]
Which are the issues?

**Comment by eddelbuettel** [comment]
As the discussion is now entirely within-FC and without overlap to RcppArmadillo, may I suggest it be moved to another venue?  Please feel free to link back here as you see fit.  Thanks so much.
