### ISSUE TITLE
float matrix multiplication

### ISSUE THREAD

**Issue by YinLiLin** [RcppCore/RcppArmadillo#304]
Hi,

I am using RcppArmadillo to implement a float matrix multiplication, when I do ```sourceCpp("test.cpp")```, it gives an error as following:
```r
/tmp/Rtmpk7wqDQ/sourceCpp-x86_64-pc-linux-gnu-1.0.4.6/sourcecpp_3867f37310913/sourceCpp_28.so: undefined symbol: ssyrk_
```
Here is an small example ("test.cpp") which can reproduce the above error:
```c
#include <RcppArmadillo.h>

// [[Rcpp::plugins(cpp11)]]
// [[Rcpp::depends(RcppArmadillo)]]

using namespace std;
using namespace Rcpp;
using namespace arma;

// [[Rcpp::export]]
SEXP myf(const arma::mat a){
	arma::fmat a1(a.n_rows, a.n_cols);
	for(int i = 0; i < a.n_rows; i++){
		for(int j = 0; j < a.n_cols; j++)
		a1(i, j) = a(i, j);
	}
	arma::fmat b = a1.t() * a1;
	return Rcpp::wrap(b);
}
```
I find it works fine in Microsoft R Open, but fails in standard R, could you please help to figure it out?
Thanks.

**Comment by eddelbuettel** [comment]
"That can happen."

Let me explain.  R uses LAPACK and BLAS, and depending on where/how you use R, different LAPACK/BLAS implementations are used.  You can see which one is active on your system via (among other commands) `sessionInfo()`.  Now, R itself, to provide a baseline and minimal support it needs, ships its own _subset_ of LAPACK and BLAS.  It is a _subset_ because R itself only uses `double` (64 bit) and `int` (32 bit) (plus `complex`) but, and that is important here, not 32 bit `float` or 64 bit `int` (and no unisgned ints of any size).

As R does not use `float`, its LAPACK does not support it.  Hence the error in standard R: no routines for `float`, and hence a linker error.  Microsoft R use the MKL (which one can use on other systems too, see [my repo with a script here](https://github.com/eddelbuettel/mkl4deb) for Ubuntu and Debian) which has full support so the float example can compute.

My (LInux) machine uses OpenBLAS, your example also computes.  So in sum, this is not really a restriction in RcppArmadillo because we only ever promise to support `int`, `double` and `complex`.   I hope you understand.

You can still use such code, you just have to make sure you have a complete LAPACK/BLAS around.

**Comment by YinLiLin** [comment]
Got it. Many thanks for your detailed explanation.
