### ISSUE TITLE
use system armadillo

### ISSUE THREAD

**Issue by Alessandro-Barbieri** [RcppCore/RcppArmadillo#338]
I'm packaging this package for gentoo and we have a policy to not bundle external libraries. Is it possible to make this package recognize and already present armadillo installation and link to it/use it's headers?

**Comment by eddelbuettel** [comment]
"It's complicated."  Feel free to patch it as you see fit. I have been a Debian maintainer since 1995, and (in this package as as an "upstream") actively contradict the same policy we have (for "vertical integration" with in distro) because I as the RcppArmadillo put more weight on the "horizontal integration" across distros).  Debian has Armadillo, and I package RcppArmadillo, and they are not linked. It is similar for Eigen, BH (== Boost Headers) and a few other packages.

In theory, this could be better. So if you come up with something, let us know,  In practice, it is hard, and what we have done here served us and every user well for a decade so I am going to close this now.  Feel free to reopen if you feel strongly about though it may not move my position
