### ISSUE TITLE
Passing NA matrices causing issues

### ISSUE THREAD

**Issue by somakd** [RcppCore/RcppArmadillo#368]
I want to write a function where I pass (references to) three matrices so that the last one stores the product of the first two matrices.

It seems that if I initialize the third matrix by NAs I get back a matrix of NAs. On the other hand, if I change even a single value of z to something non-NA, I get the desired result.

```
#include <RcppArmadillo.h>
//[[Rcpp::depends(RcppArmadillo)]]
//[[Rcpp::export()]]
int mm(const arma::mat &x, const arma::mat &y, arma::mat &z)
// Compute z = x*y
{
  z = x*y;
  return(0);
}

/***R
x = matrix(1,2,3)
y = matrix(1,3,4)

z = matrix(NA,2,4) # Initialize with NAs
mm(x,y,z)
print(z) # Expecting a matrix with all entries but get a matrix of NAs


z[1,1] = 2441139 # Some random number
mm(x,y,z)
print(z) # Now we get the desired result

*/

```

**Comment by eddelbuettel** [comment]
You cannot do that. See question 5.1 of the Rcpp FAQ, and keep in mind that _all_ interfaces with R are of the `SEXP .Call(funcname,  SEXP A, SEXP B, ...)` variety and _a `SEXP` is not an `arma::mat` so you always get copy involved.

So you need to return the result, which is common (and no, it is not costly because as just shown what we return is `SEXP` which is a moderately small data structure containing a _pointer_ to the actual payload)

```r
> Rcpp::cppFunction("arma::mat mm(arma::mat x, arma::mat y) { arma::mat z = x * y; return(z);}", depends="RcppArmadillo")
> x <- matrix(1,2,3)
> y <- matrix(1,3,4)
> z <- mm(x, y)
> z
     [,1] [,2] [,3] [,4]
[1,]    3    3    3    3
[2,]    3    3    3    3
> 
```

I think we can probably close this.

**Comment by somakd** [comment]
Thanks! I appreciate your response.
