### ISSUE TITLE
Fails to compile vs 

### ISSUE THREAD

**Issue by YuriWerewolf** [RcppCore/RcppArmadillo#403]
Hi all,

here is my session info:
> sessionInfo()
```
R version 4.1.2 (2021-11-01)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Linux Mint 21.1

Matrix products: default
BLAS/LAPACK: /usr/lib/x86_64-linux-gnu/libflexiblas.so.3.3

locale:
 [1] LC_CTYPE=en_IE.UTF-8       LC_NUMERIC=C               LC_TIME=en_IE.UTF-8        LC_COLLATE=en_IE.UTF-8     LC_MONETARY=en_IE.UTF-8    LC_MESSAGES=en_IE.UTF-8   
 [7] LC_PAPER=en_IE.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C             LC_MEASUREMENT=en_IE.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.10       fansi_1.0.4       utf8_1.2.3        dbplyr_2.3.0      dplyr_1.1.0       assertthat_0.2.1  R6_2.5.1          lifecycle_1.0.3   DBI_1.1.3        
[10] magrittr_2.0.3    pillar_1.8.1      rlang_1.0.6       cli_3.6.0         rstudioapi_0.14   vctrs_0.5.2       generics_0.1.3    tools_4.1.2       bit64_4.0.5      
[19] glue_1.6.2        bit_4.0.5         compiler_4.1.2    pkgconfig_2.0.3   tidyselect_1.2.0  tibble_3.1.8      RClickhouse_0.6.4
```

When trying to install RcppArmadillo I get the following error:
```
g++ -std=gnu++11 -shared -L/usr/lib/R/lib -Wl,-Bsymbolic-functions -flto=auto -ffat-lto-objects -flto=auto -Wl,-z,relro -o RcppArmadillo.so RcppArmadillo.o RcppExports.o fastLm.o -fopenmp -llapack -lblas -lgfortran -lm -lquadmath -L/usr/lib/R/lib -lR
/usr/bin/ld: cannot find -llapack: No such file or directory
/usr/bin/ld: cannot find -lblas: No such file or directory
collect2: error: ld returned 1 exit status
make: *** [/usr/share/R/share/make/shlib.mk:10: RcppArmadillo.so] Error 1
ERROR: compilation failed for package ‘RcppArmadillo’
```

My guess is that because i have updated BLAS/LAPACK it fails to see new library.
Is it possible to compile it vs /usr/lib/x86_64-linux-gnu/libflexiblas.so.3.3 ? And if so how can I do it?

And if if it is not possible how do I compile RcppArmadillo pls?

Thanks

**Comment by eddelbuettel** [comment]
On Debian and Ubuntu (and that should carry over to Mint) all you needed for a decade or longer is r-base-dev because it brings libblas-dev and liblapack-dev in.  That is how R is built (as a package), that is what it expects and where your command failed.  Note that the distributions also have r-cran-rcpparmadillo so you would not have to compile -- but can of course as that is how I develop the RcppArmadillo package.  

But from a casual glance from a distance it seems like you broke your installation by injecting flexiblas.  If you depart from the standard pattern the distribution sets up (you are _of course_ free to do so!) you _may_ have to recompile R.  I happen to be the maintainer of R on Debian, and quite involved with Rcpp and RcppArmadillo.  "It just works."  I also once described [in detail how to switch LAPACK/BLAS installations](https://cloud.r-project.org/web/packages/gcbd/vignettes/gcbd.pdf) (that is a little dated I admit but the interface described there is what I describe in this email).   Look story short:  you may have to do some extra work to have flexiblas work.  Maybe you just need it to provide the LAPACK and BLAS development hooks -- I don't know as I haven't used flexiblas yet.

I propose we close this as it all points to the error being at your end.

**Comment by eddelbuettel** [comment]
Or in other words:
- R expects there to be what the libblas-dev and liblapack-dev provide: the ability to link with -llapack -lblas
- This failed for you as seen
- As described in the linked vignette for package `gcbd` we have been able to rotate and switch between various LAPACK and BLAS libraries with relative ease for many years
- Now flexiblas does that too and governs so maybe you need to work out how to make flexiblas adhere to BLAS and LAPACK compatibility scheme and then you can do too what `gcbd` describe: mix, match, and switch

Currently you are not. I think that either your usage error / incomplete setup as "run-time" is not the same as "compile-time".  But it's not an error with R or (Rcpp)Armadillo.

**Comment by YuriWerewolf** [comment]
Thanks for the responses Dirk, I will follow them and close this issue.
