### ISSUE TITLE
Question about SIMD Optimization

### ISSUE THREAD

**Issue by pati-ni** [RcppCore/RcppArmadillo#404]
According to [this guide](https://arma.sourceforge.net/faq.html#speed) to get these optimizations when working with native armadillo library we need to pass compiler parameters. How does this translate to RcppArmadillo? Are these optimizations already enabled?

**Comment by eddelbuettel** [comment]
RcppArmadillo is _header-only_ (apart from the example / illustration that is `fastLm()`) so it is up to your package to organize its compiler flags.  

The _default_ configuration we set in the headers _should_ not get in the way.  If you find otherwise, let us know!

Demos with SIMD turned on would be welcome, this may make for a nice post at the [Rcpp Gallery](https://gallery.rcpp.org/). Maybe you can write something up?

**Comment by pati-ni** [comment]
After performing some benchmarks independently (outside of R) with Rcpp
and RcppArmadillo it looks like that the proposed optimizations do not
make a difference on a fairly recent compiler (gcc 12) with
C++14.

If I link with -O0 which significantly slows down the benchmark. However
I did not look into the assembly to determine which conditions use or do
not use SIMD commands. Since C++ compilation in R by default has -O1 I
do not think there are a lot to benefit from a guide. Feel free to close
the issue.

**Comment by eddelbuettel** [comment]
I had a similar hunch based on the work we have done with RcppSimdJson (which is crazy fast thanks to really well engineered code inside).  But it does not require 'magic switches' -- the modern compiler mostly know already.  So yes: -O2 or -O3 coupled with -march=native will (on suitable modern hardware) already all that is there and the package should not leave anything behind.  Which, I think, your tests confirmed.  So closing this.
