### ISSUE TITLE
cube sum edge cases

### ISSUE THREAD

**Issue by rvalieris** [RcppCore/RcppArmadillo#76]
Hello,

I think I have found a bug on the cube code that appears with specific dimensions.
I have created a small test case here: https://gist.github.com/rvalieris/24ad10caac132757ff31

The problem is on cube_sum1, depending on the dimensions of the cube(slices=1 seems to be the rule) different things happen, examples:
```
40x16x1: no errors, wrong result
80x16x1: error: addition: can't interpret cube with dimensions 1x1072642625x1 as a matrix with dimensions 16x1
90x21x1: valgrind errors, crash
99x21x1: valgrind errors, no crash, wrong result
99x21x2: no errors, right result
```
I'm comparing the results with cube_sum2 which is what I intended cube_sum1 to do.
This was tested on RcppArmadillo_0.6.400.2.2

At this point I am not sure what the source of the problem is.., is this my misuse of tube(), bug on Rcpparmadillo, armadilo itself or something else ?

**Comment by eddelbuettel** [comment]
Thanks for the report.  Can you try the following:

- third dimension other than 1 ?  maybe there is an implicit reduction (shouldn't be)
- try Armadillo without RcppArmadillo?  I suspect the bug is in the translation layer
- help me put a set of eyes on the R -> Armadillo mapping? 

The Cube converter is reasonably new as I recall...

**Comment by rvalieris** [comment]
Hey there,
from what I have tried slice>1 seems to work fine,
I will try to write this in pure armadillo but I don't think the problem is on the construction of the cube, this function was being called by another cpp function and the cube argument was being passed as a reference, also the cube_sum2 is receiving the same argument and works fine.

**Comment by rvalieris** [comment]
indeed, I can reproduce the problem in pure armadillo, so I guess I will report the bug there instead.

thanks for your attention.

**Comment by eddelbuettel** [comment]
You caught me when I was running out of the house, I since looked at your example more closely.  

And for once ... in all these years with Armadillo it does indeed seem to appear at Conrad's end.  Your examples are well crafted -- standard reductions of those Cubes.  

Tell him I said Hi. I need to send him an email too...
